---
- name: Template Playbook
  hosts: servers
  become: true
  gather_facts: true
  tasks:
    - name: First step
      ansible.builtin.ping:

    - name: Second step
      ansible.builtin.include_role:
        name: template_role
...
