---
argument_specs:
  main:
    short_description: Main entry point for the example role
    description:
      - This is the main entrypoint for the C(example) role.
      - Here we can describe what this entrypoint does in lengthy words.
      - Every new list item is a new paragraph. You can have multiple sentences
        per paragraph.
    author:
      - Your Name
    options:
      example_int:
        type: "int"
        required: false
        default: 42
        description:
          - "The integer value, defaulting to 42."
          - "This is a second paragraph."

      example_str:
        type: "str"
        required: true
        description: "The string value"
...
